// backend/prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding questions...");

  // Clear existing questions if any
  await prisma.question.deleteMany({});

  const questions = [
    // Afaan Oromoo Subject
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Dureettiifi Burqaan 'barattoota kutaa sagaliiti'. Hima kana keessatti kan jala sararame (barattoota kutaa sagaliiti) maali?",
      options: ["Gaalee maqibsaati", "Gaalee durduubeeti", "Gaalee gochimaati", "Gaalee maqaati"],
      correctOptionIndex: 3,
      explanation: "Gaaleen 'barattoota kutaa sagaliiti' jedhu maqaa (barattoota) irratti waan hundaa'uuf gaalee maqaati.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Bamaqaa ilaalchisee kamtu soba?",
      options: [
        "Ramaddii agarsiisa.",
        "Fufiilee maxxanfachuun danoomina agarsiisu.",
        "Bakka maqaa bu'uun tajaajila kenna.",
        "Waliin dubbii keessatti irra deddeebii hambisuuf oola."
      ],
      correctOptionIndex: 1,
      explanation: "Bamaqaan (Pronoun) uumamaan danoomina kan qabu (fkn. isaan, nuti) malee fufii danoomaa (fkn. -oota) maxxanfachuun miti kan inni danoomu.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Boonaan, 'atattamaan' gara mana barumsaa deeme. Jechii jala sararame tajaajila maali kenna?",
      options: ["Maqaa", "Maqibsaa", "Gochimaa", "Gochibsaa"],
      correctOptionIndex: 3,
      explanation: "Jechi 'atattamaan' jedhu gochi (deemuu) haala kamiin akka raawwatame waan ibsuuf gochibsaa (adverb) dha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Hima keessatti yaada handhuura keeyyatichaa qabatee kan argamu kami?",
      options: ["Hima callaa", "Hima murtaawaa", "Hima ijoo", "Hima goolabaa"],
      correctOptionIndex: 2,
      explanation: "Hima ijoon (topic sentence) yaada bu'uuraa ykn handhuura keeyyatichaa kan of keessatti qabatuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Jechoota kennamaniif filannoo hiika sirrii qabate filachuun deebisi: 'shakkii'",
      options: ["karaa", "mamii", "sodaa", "rifaatuu"],
      correctOptionIndex: 1,
      explanation: "'Shakkii' jechuun dhimma tokkorratti guutummaatti amanuu dhabuu, mamiifi waldhaansoo yaadaa jechuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Jechoota kennamaniif filannoo hiika sirrii qabate filachuun deebisi: 'cunqursaa'",
      options: ["roorroo", "dallansuu", "mormii", "komii"],
      correctOptionIndex: 0,
      explanation: "Cunqursaan dhiibbaa, miidhaafi roorroo qaamni tokko humnaan nama biroorratti raawwatu ibsa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Dalagaalee dhala namaa walxaxaa ta'e ibsuuf5 murteessaan kami?",
      options: ["Afaan", "nama barate", "saayikoloojii", "falaasama"],
      correctOptionIndex: 0,
      explanation: "Afaan meeshaa bu'uuraa dhalli namaa yaada, fedhii, aadaafi dalagaa isaa walxaxaa ta'e hawaasa keessatti ittiin ibsatuufi ittiin walii galuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Keeyyata lammaffaa keessatti 'Amala isaa qorachuun kan danda'amu karaa afaan isaatiin' kan jedhu keessatti bamaqaan 'isaa' jedhu maal agarsiisa?",
      options: ["amantii", "hawaasa", "aadaa", "afaan"],
      correctOptionIndex: 1,
      explanation: "Bamaqaan 'isaa' jedhu maqaa bakka bu'uun tajaajila. As keessatti amalli qoratamuu fi kan afaan ittiin dubbatu 'hawaasa' waan ta'eef, jechi isaa jedhu hawaasa agarsiisa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Akka hayyuuleen dhimma afaanii irratti ibsanitti, afaaniif maal ibsa?",
      options: [
        "Afaaniifi aadaa",
        "Afaaniifi uummanni walqabachuu",
        "hawaasa",
        "Afaaniif hiikaan adda addaa kennamuu"
      ],
      correctOptionIndex: 3,
      explanation: "Keeyyatichi hayyuuleen garaa garaa haala qo'annoo isaaniirratti hundaa'uun afaaniif hiika adda addaa akka kennan ibsa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Mata duree dubbisa maalummaa afaaniifi faayidaa isaa ibsu kami?",
      options: ["Maalummaa afaanii", "Guddina afaanii", "afaaniifi uummata", "mallattoo ta'uu afaanii"],
      correctOptionIndex: 0,
      explanation: "Barreeffamichi guutuun isaa afaan maali, hayyuuleen akkamitti ibsu, akkasumas faayidaan isaa maal akka ta'e waan addeessuuf, mata dureen mijataan 'Maalummaa Afaanii' dha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Afaan ilaalchisee yaadni dogoggoraa kami?",
      options: [
        "Afaaniif hiika tokko kennuun quubsaa miti.",
        "Afaan aadaa ni calaqqisiisa.",
        "Hayyuuleen hundi hiika tokko kennaniiru.",
        "Afaan yaada waljijjiiruuf ni gargaara."
      ],
      correctOptionIndex: 2,
      explanation: "Ogeeyyiin afaanii, antiroopoloojistoonni, fi saayikoloojistoonni haala qorannoo isaaniirratti hundaa'uun hiika garaa garaa afaaniif kennaniiru; hiika tokko qofa miti.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Yaadni 'Afaan baataa aadaati' jedhu maal ibsuufi?",
      options: [
        "Aadaa ba'aa ta'uu",
        "Aadaan uummataa kan ifu ykn daddarbu afaaniin ta'uu.",
        "Afaaniif hiika kennuun rakkoo ta'uu",
        "Eenyummaan saba tokkoo amantii isaa qofaan kan ifu ta'uu."
      ],
      correctOptionIndex: 1,
      explanation: "Afaan aadaa saba tokkoo dhalootaa gara dhalootaatti baatee waan dabarsuuf ibsa kana fayyadamna.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Aadaa hawaasaa - amala isaa qorachuun kan danda'amu karaa afaan isaati kanneen jedhan eenyufa'i?",
      options: ["Hayyuulee seenaa", "Antiroopoloojistoota", "Hayyuulee afaanii", "Saayikoloojistoota"],
      correctOptionIndex: 1,
      explanation: "Antiroopoloojistoonni qo'annoo hawaasaa, aadaa, fi dhala namaarratti waan xiyyeeffataniif, amala hawaasa tokkoo qorachuuf afaan akka meeshaatti fayyadamu.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Afaan meeshaa waliigaltee dhala namaa kan sagaleelee dubbii bu'uura godhachuum tajaajilu ta'uu kanneen ibsan eenyu?",
      options: ["Hayyuulee aadaa", "Saayikoloojistoota", "Hayyuulee afaanii", "Antiropoloojistoota"],
      correctOptionIndex: 2,
      explanation: "Hayyuuleen afaanii (Linguists) caasaa afaanii, sagalee dubbiifi seera afaanii qorachuurratti waan xiyyeeffataniif hiika akkasii kennu.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Hiikni jechama 'fuula bade' jedhuu kami?",
      options: ["Fuula fokkise", "Jibbe", "Gammade", "Finniisa godhate"],
      correctOptionIndex: 1,
      explanation: "Namni tokko 'fuula bade' yoo jedhamu, haalli dhiyaateef waan itti hin tolleef ykn waan aareef ifaajee fuula isaaratti agarsiise jechuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Hiikni jechama 'miicee micciire' jedhuu kami?",
      options: ["Hubatee ilaale", "dhiqee uffate", "tuqee ilaale", "utaalee cabe"],
      correctOptionIndex: 0,
      explanation: "'Miicee micciire' hiikni jechamaa isaa dhimma tokko kallattii maraan qorachuu, gadi fageenyaan xiinxaluufi hubatee ilaaluu agarsiisa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "\"Ilkaaniin bula.\" Hiika jechama kanaan kan walfakkaatu kami?",
      options: ["kolfa jaallata", "ilkaan dhiyaana isaati", "dhugaa dubbata", "fakkeessee jiraata"],
      correctOptionIndex: 3,
      explanation: "'Ilkaaniin bula' jechuun namni tokko keessa isaa dhugaa biraa qabatee, garuu namatti mul'achuuf qofa alaan ilkaan isaa agarsiisee (kolfee) fakkeessee jiraachuu agarsiisa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "\"Cululleen waan argatte butti.\" Ergaan mammaaksa kanaa maali?",
      options: ["gaabbii", "hawwii", "hiree", "jaalala"],
      correctOptionIndex: 0,
      explanation: "Cululleen waan argatte hunda osoo hin filatiin waan buttuuf, bofa buttee miidhamuu dandeessi. Ergaan isaas namni osoo hin hubatiin waan argate hunda fudhatu booda 'gaabbii' keessa bu'a.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Filannoo tartiiba sirrii jechoota kennaman qabatanii hima sirrii ijaaruu danda'an hordofuun filadhu. Jechoota: daa'immaniif¹ / barbaachisaadha² / nyaachuun³ / madaalamaa⁴ / nyaata⁵ / guddinaafi⁶ / sammuu⁷ / dagaagina⁸",
      options: [
        "3, 4, 5, 6, 7, 8, 2, 1",
        "6, 4, 3, 5, 8, 7, 1, 2",
        "5, 4, 3, 6, 8, 7, 1, 2",
        "5, 3, 4, 6, 8, 7, 1, 2"
      ],
      correctOptionIndex: 2,
      explanation: "Caasaan hima kanaa yoo sirreeffamu: 'Nyaata(5) madaalamaa(4) nyaachuun(3) guddinaafi(6) dagaagina(8) sammuu(7) daa'immaniif(1) barbaachisaadha(2).' ta'a.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 1: Caasluga, Dubbisaafi Afoola",
      questionText: "Filannoo tartiiba sirrii jechoota kennaman qabatanii hima sirrii ijaaruu danda'an hordofuun filadhu. Jechoota: kabaja¹ / dubartiin² / Sirna³ / guddaa⁴ / keessatti⁵ / Gadaa⁶ / qabdi⁷",
      options: [
        "3, 6, 2, 1, 5, 4, 7",
        "1, 7, 3, 6, 4, 2, 3",
        "3, 6, 2, 1, 4, 5, 7",
        "3, 6, 5, 2, 1, 4, 7"
      ],
      correctOptionIndex: 3,
      explanation: "Tartiibni caasluga Afaan Oromoo hordofuun yoo ijaaramu: 'Sirna(3) Gadaa(6) keessatti(5) dubartiin(2) kabaja(1) guddaa(4) qabdi(7).' ta'a.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Lammiin abbaasaa 'lukkarratti kufee' araara gaafate. Gaaleen jala sararame (lukkarratti kufee) kami?",
      options: ["Gaalee durduubee", "Gaalee maqaa", "Gaalee maqibsaa", "Gaalee gochimaa"],
      correctOptionIndex: 3,
      explanation: "Gaaleen kun gochima (kufee) irratti waan hundaa'uuf, akka gaalee gochimaatti (Verb Phrase) fudhatama.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Gaaleewwan armaan gadii keessaa gaalee maqaa kan hinta'iin kami?",
      options: ["haadha keenya", "Mana dhugaatii", "mana citaa", "ilkaan kaarruu"],
      correctOptionIndex: 3,
      explanation: "'haadha keenya', 'mana dhugaatii', 'mana citaa' hundi isaanii maqaa walqabatoo (Noun Phrases) ta'aniidha. 'Kaarruu' amala ilkaanii (Adjective) waan ibsuuf adda ta'uu danda'a.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Dhamjechi matima agarsiisuuf maqaalee dubbachiiftuu dheeraan xumuraman irratti galu kami?",
      options: ["-ni", "-i", "-n", "-ti"],
      correctOptionIndex: 2,
      explanation: "Maqaaleen dubbachiiftuu dheeraan xumuraman (fkn. Caalaa, fardaa) yeroo matima ta'an '-n' maxxanfatu (Fkn. Caalaan, fardaan).",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "\"Inni haadhaaf huccuu bite\" kan jedhu keessatti aantimni kallattii kami?",
      options: ["haadha", "haadhaaf", "huccuu", "bite"],
      correctOptionIndex: 2,
      explanation: "Hima kana keessatti wanti kallattiin bitame 'huccuu' (Direct Object) dha. 'Haadhaaf' aantima alkallattii (Indirect Object) dha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "\"Kaayyoo qabattee kaate tokko xumuruuf, yoo jabaattee hojjette bakka gaariitu si eeggata.\" Hima kana keessatti 'si' kan jedhu ilaalchisee kan dhugaa ta'e kami?",
      options: [
        "ramaddii lammaffaa ta'ee koorniyaa addaa ni baasa",
        "ramaddii sadaffaa agarsiisti",
        "ramaddii sadaffaa ta'ee koorniyaa addaa hin baasu",
        "ramaddii lammaffaa koorniyaa hin foo'u"
      ],
      correctOptionIndex: 3,
      explanation: "Bamaqaan 'si' jedhu ramaddii lammaffaa ta'ee, dhiiraafis dubartiifis walqixa waan tajaajiluuf koorniyaa addaan hin foo'u.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Jechi \"kiraasassaabdummaa\" jedhu birsagaan yoo qoqqoodamu kami?",
      options: [
        "Kiraa-sa-ssab-dum-maa",
        "Ki-raa-sas-sab-dum-maa",
        "ki-raa-sas-sab-du-mmaa",
        "ki-raa-sas-sabdu-mmaa"
      ],
      correctOptionIndex: 1,
      explanation: "Qoqqoodiinsa birsagaa (Syllabification) keessatti qubeewwan jabaatan (fkn. ss) iddoo lamatti qoodamu. Kanaaf 'sas-sab' ta'a.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Isaa¹ / namni² / qajeelaa³ / fedha⁴ / yaada⁵ / horatu⁶ / lammiin⁷ / akka⁸ / qabu⁹. Tartiiba sirrii hima ijaaruu danda'u filadhu:",
      options: [
        "4, 6, 8, 1, 7, 9, 3, 5, 2",
        "7, 5, 3, 9, 2, 4, 8, 1, 6",
        "2, 5, 3, 9, 7, 1, 8, 6, 4",
        "2, 5, 7, 9, 3, 1, 8, 6, 4"
      ],
      correctOptionIndex: 2,
      explanation: "Hima sirrii: 'Namni(2) yaada(5) qajeelaa(3) qabu(9) lammiin(7) isaa(1) akka(8) horatu(6) fedha(4).'",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Kanneen armaan gadii keessaa tokko malee hundi eebba nama nama araarseen jedhamuudha:",
      options: [
        "Gammachuu hindhabinaa!",
        "Jaarsa araaraa ta'a!",
        "Dhugaan isin jalaa hindhokatiin!",
        "Dubbadhaa dhugaa argadhaa!"
      ],
      correctOptionIndex: 0,
      explanation: "'Jaarsa araaraa ta'a', 'Dhugaan isin jalaa hindhokatiin', fi 'Dubbadhaa dhugaa argadhaa' eebbawwan kallattiin araaraafi dhugaa baasuun walqabataniidha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "\"Sareen fira naachaa qabdu, waaree bishaan dhugdi.\" Ergaan mammaaksa kanaa maali?",
      options: ["tuffii", "obsa", "abdii", "fakkaachuu"],
      correctOptionIndex: 2,
      explanation: "Namni of duuba humna jabaafi fira qabu, soda malee abdiifi of-itti amanamummaan socho'a kan jedhu agarsiisa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Mammaaksi adda ta'e kami?",
      options: [
        "Gowwaa kofalchiisanii ilkaan lakkaa'u.",
        "Ganna baatii sadiif bofaafi buutii wajjiin jiraatu.",
        "Hamma farda bira ga'anitti harree yaabbatu.",
        "Baranaaf malee sombi kan sareeti."
      ],
      correctOptionIndex: 0,
      explanation: "Filannoowwan B, C, fi D hundi isaanii obsaafi haala yeroof jiru danda'anii dabarsuurratti xiyyeeffatu. 'A' garuu waa'ee nama gowwoomsuu agarsiisa.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Hiika jechamoota armaan gadiitti kennaman filadhuu deebisi: \"ciqilee jabaata\"",
      options: ["ni joora", "doqna dha", "cimaa dha", "arjaa dha"],
      correctOptionIndex: 1,
      explanation: "Afaan Oromoo keessatti namni ciqileen isaa jabaataa ta'e nama wanta qabu namaaf hin kennine (stingy) jechuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Hiika jechamoota armaan gadiitti kennaman filadhuu deebisi: \"aagii tufe\"",
      options: ["dallansiise", "firoome", "itti mufate", "dhiifama godhe"],
      correctOptionIndex: 3,
      explanation: "'Aagii tufe' jechuun aarii isaa dhiise, qabbanaa'e, araarameefi dhiifama godhe jechuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Haala barreeffama kanaatti dogoggorri akka amala gadheetti hin ilaaalamne maaliif?",
      options: [
        "Dogoggorri yeroo hundaayyuu waan uumamuuf.",
        "Dogoggorri beekumsaan ala tasa waan uumamuuf.",
        "Dogoggorri waan irra darbamuuf.",
        "Dogoggoraan ala jiraachuun waan hin danda'amneef."
      ],
      correctOptionIndex: 1,
      explanation: "Akka dubbisichaatti, daa'imni beekumsaan osoo hin taane tasa yookiin walta'iinsa qaamaa dhabuu irraan kan ka'e waan balleessuuf dogoggorri akka amala gadheetti hin fudhatamu.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Mallattoon gaalee ''garuu,...'' jedhutti aanee dhufuu qabu kami?",
      options: ["Mallattoo tuftuu (...)", "Qoodduu xiqqaa (,)", "Qoodduu jabaa (;)", "Tuqaa (.)"],
      correctOptionIndex: 1,
      explanation: "Jechoota walqabsiisoo kan akka 'garuu', 'kanaafuu' jedhan booda yeroo hunda qoodduu xiqqaa (comma) tu fayyadamama.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Tooftaa tokkoffaan ittiin amala gadhee sirreessan isa kami?",
      options: [
        "Daa'ima amala gadhee qabutti aaruu dhiisuu.",
        "Daa'ima amala gadhee qabu sana dhimma hojjetamurraa ittisuu.",
        "Amala gadhee daa'imichi mul'isu tuffatanii bira darbuu.",
        "Faay'idaa daa'ima amala gadhee qaburraa hir'isuu."
      ],
      correctOptionIndex: 3,
      explanation: "Akka barreeffama dhiyaateetti, tooftaan inni jalqabaa amalli gadheen yeroo mul'atu faayidaa yookiin wanta daa'imni sun jaallatu irraa hir'isuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Gaaleen \"... biraati...\" jedhu yoo gaalee kamiin bakka bu'ame sirrii ta'a?",
      options: ["Lammataati", "Sadaffaati", "Jaalatamaati", "Beekamaati"],
      correctOptionIndex: 0,
      explanation: "'Tooftaa biraati' jechuun tooftaa kan biroo yookiin filannoo lammataati jechuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Mata dureen barreeffama kanaa kanneen armaan gadii keessaa kam ta'uu danda'a?",
      options: [
        "Amala gadhee daa'immanii sirreessuu",
        "Dogoggorri amala gadhee miti",
        "Garaagarummaa amala gadheefi wallaalaa",
        "Mormii amala gadheerratti ka'u."
      ],
      correctOptionIndex: 0,
      explanation: "Barreeffamichi guutummaatti tooftaalee amala gadhee daa'immanii ittiin sirreessan irratti waan xiyyeeffatuuf kana ta'a.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Ijoon keeyyata lammaffaa hima kami?",
      options: ["Hima tokkoffaa", "Hima lammaffaa", "Hima sadaffaa", "Hima arfaffaa"],
      correctOptionIndex: 0,
      explanation: "Keeyyatichi 'Amala gadhee raawwatame tuffatanii irra darbuun tooftaa biraati' jechuun hima ijoo isaa jalqaba irratti ibseera.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Kutaalee xalayaa keessaa dhimma xalayicha akka barreessinuuf nu kakaaseefi dhimma barreessuu barbaanne itti dhiyeessinu maal jedhama?",
      options: ["Teessoo", "Keeyyata seenessaa", "Qaama", "Cufaa"],
      correctOptionIndex: 2,
      explanation: "Qaamni xalayaa (Body of the letter) iddoo ergaaniifi dhimmi guddaan xalayichaa itti barreeffamuudha.",
      isFree: false,
    },
    {
      subject: "Afaan Oromoo",
      topic: "Set 2: Seerluga, Mammaaksaafi Hubannoo Dubbisaa",
      questionText: "Abaaboon obboleettii Tolashiiti. Mucaan Abaaboo Soolan jedhama. Kan Tolashii Lookoo jedhamti. Lookoofi Soolan maal walii ta'u?",
      options: ["Adaadaa", "Eessuma", "Wasiila", "Durbii"],
      correctOptionIndex: 3,
      explanation: "Ilmaaniifi intalloottan obboleettota lama gidduu jiran durbii waliif ta'u.",
      isFree: false,
    },

    // Herrega Subject
    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "Yoo f(x) = 2x + 5 fi g(x) = x - 3 ta'an, f(g(4)) meeqa ta'a?",
      options: ["5", "7", "13", "11"],
      correctOptionIndex: 1,
      explanation: "Jalqaba g(4) barbaadna: g(4) = 4 - 3 = 1. Sana booda f(1) barbaadna: f(1) = 2(1) + 5 = 7.",
      isFree: true,
    },
    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "Gatii x herrega equation kanaa argadhu: 3x - 7 = 11?",
      options: ["4", "5", "6", "8"],
      correctOptionIndex: 2,
      explanation: "7 gara mirgaatti dabalamee: 3x = 18 ta'a. 3'n yoo qoodamu: x = 6 ta'a.",
      isFree: true,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Kofni keessoo rog-jaallaa (hexagon) maalitti qixxaa'a?",
      options: ["digrii 360", "digrii 540", "digrii 720", "digrii 900"],
      correctOptionIndex: 2,
      explanation: "Foormulaan (n - 2) * 180 dha. Rog-jaallaa (n=6) ta'eef: (6 - 2) * 180 = 4 * 180 = 720 digrii ta'a.",
      isFree: true,
    },

    // Saayinsii waligalaa Subject
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Utubaan alaabaa tokko gaaddidduu meetira 12 uuma. Kanuma waliin mukni dhihoo jiru, kan dheerinni isaa meetira 5 ta'e, gaaddidduu meetira 4 uuma. Dheerinni utubaa alaabaa kanaa meeqa?",
      options: ["20m", "15m", "9cm", "18m"],
      correctOptionIndex: 1,
      explanation: "Gaaddiddoo lamaan yeroo tokkotti waan uumamaniif, sadarkaan aduu wal-fakkaataadha, kanaafuu rog-sadeewwan lamaan wal-fakkaatu (similar triangles): dheerinni utubaa / gaaddidduu utubaa = dheerinni muka / gaaddidduu muka. h/12 = 5/4 → h = (5×12)/4 = 15m.",
      isFree: true,
    },
    {
      subject: "Herrega",
      topic: "Piroobaabiliitii",
      questionText: "Daayiiwwan lama al tokko darbataman. Carraan ta'uumsaa ida'amni lakkoofsota fuulota isaanii ol-garagalan 9 ta'u meeqa?",
      options: ["1/4", "1/9", "1/6", "1/36"],
      correctOptionIndex: 1,
      explanation: "Daayii lama darbachuun haala hunda 36 (6×6) qaba. Ida'amni fuulota lamaanii 9 ta'uu kan danda'u: (3,6),(4,5),(5,4),(6,3) — haala 4. Carraan = 4/36 = 1/9.",
      isFree: true,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Qabeen piriizimii hundeen isaa rog-sadee kofa sirrii ta'e, dheerinni rogoota isaa 3cm, 4cm, 5cm fi oleen isaa 12cm ta'e, piriizimichaa qabeen meeqa?",
      options: ["72cm³", "144cm³", "120cm³", "156cm³"],
      correctOptionIndex: 0,
      explanation: "Bal'inni hundee (rog-sadee kofa sirrii, cinaawwan 3 fi 4) = (1/2)×3×4 = 6cm². Qabeen piriizimii = bal'ina hundee × ol'aanaa = 6×12 = 72cm³.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Danaa keessatti O'n handhuura geengoo, S(<AOB)=70°. S(<OBA) meeqa?",
      options: ["20°", "35°", "55°", "70°"],
      correctOptionIndex: 2,
      explanation: "Rog-sadee OAB dhaabbataadha (OA=OB=raadiyeesa). Kofawwan hafan lamaan walqixa: (180−70)/2 = 55°.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "(3xy + 2y)(−2x + 6xy) + 4xy + 6x²y = ?",
      options: ["12xy² + 18x²y²", "6xy² + 30x²y²", "18x²y² + 6xy²", "12xy² + 9x²y²"],
      correctOptionIndex: 0,
      explanation: "Facaasii (expand) gochuun: (3xy)(−2x)=−6x²y; (3xy)(6xy)=18x²y²; (2y)(−2x)=−4xy; (2y)(6xy)=12xy². Waliigala: −6x²y+18x²y²−4xy+12xy²+4xy+6x²y = 18x²y²+12xy², kunis 12xy²+18x²y² (filannoo A) waliin walqixa.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "Furmaata hima walcaalmaa sararaawaa 6(2−x) ≤ 3x−12 kan ta'e?",
      options: ["x ≥ 24/9", "x ≤ 24/9", "x ≤ 8", "x ≥ 0"],
      correctOptionIndex: 0,
      explanation: "6(2−x) ≤ 3x−12 → 12−6x ≤ 3x−12 → 12+12 ≤ 3x+6x → 24 ≤ 9x → x ≥ 24/9.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Piiraamidii reektaangulaawaa (rectangular pyramid) ilaalchisee kan soba ta'e kami?",
      options: ["Fuulota diriiraa 5 qaba", "Fuulota cinaachaa sadii qaba", "Varteeksota 5 qaba", "Qarqaroota 8 qaba"],
      correctOptionIndex: 1,
      explanation: "Piiraamidiin reektaangulaawaa (hundeen isaa reektaangilii) fuulota waliigalaa 5 qaba: hundee 1 + fuulota cinaachaa 4 (rog-sadee) — silaa 3 miti. Kanaafuu himni B ('fuulota cinaachaa sadii qaba') soba dha; sirriittis fuulota cinaachaa 4 qaba. Himootni A, C, fi D hundi dhugaa dha.",
      isFree: false,
    },

    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "Tuuta furmaataa hima walqixxaa |2x − 5| = 9 kan ta'e akmi?",
      options: ["{2, −7}", "{2, 7}", "{−2, 7}", "{ } ≠ ∅"],
      correctOptionIndex: 2,
      explanation: "|2x−5|=9 jechuun 2x−5=9 ykn 2x−5=−9. Tokkoffaa: 2x=14 → x=7. Lammaffaa: 2x=−4 → x=−2. Kanaafuu tuutni furmaataa {−2, 7} dha.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Lakkoofsota",
      questionText: "∛(−216/729) = ?",
      options: ["−2/3", "6/9", "−9/6", "3/2"],
      correctOptionIndex: 0,
      explanation: "−216 = (−6)³ fi 729 = 9³. Kanaafuu ∛(−216/729) = −6/9 = −2/3.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "Dheerinni hundee rektaangilii tokko dheerina olee isaa meetira 5'n caala. Naannawni isaa 42m yoo ta'e, dheerinni hundee isaa meeqa?",
      options: ["8m", "15m", "10m", "13m"],
      correctOptionIndex: 3,
      explanation: "Olee = w, hundee = w+5. Naannawwaan = 2(w + w+5) = 42 → 4w+10=42 → w=8. Hundeen = w+5 = 13m.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Koordineeshaanal Joomootrii",
      questionText: "Tuqaalee armaan gadii keessaa kan giraafii 3x − y = −2 irra hin oolle isa kami?",
      options: ["(1, 5)", "(−2, −4)", "(−2/3, 0)", "(1, 1)"],
      correctOptionIndex: 3,
      explanation: "Tuqaa tokko sarara irra jiraachuu isaa mirkaneeffachuuf 3x−y tilmaamna. (1,5): 3(1)−5=−2 ✓. (−2,−4): 3(−2)−(−4)=−2 ✓. (−2/3,0): 3(−2/3)−0=−2 ✓. (1,1): 3(1)−1=2 ≠ −2 ✗. Kanaafuu (1,1) sarara irra hin jiru.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "ABCD fi EFGH rog-afreewwan lamadha. ABCD ~ EFGH yoo ta'e, kanneen armaan gadii keessaa kamtu dhugaa?",
      options: ["AB/EF = BC/FG", "S(<A) = S(<H)", "BC/AB = FG/EF", "Hunduma"],
      correctOptionIndex: 0,
      explanation: "Rog-afreewwan wal-fakkaatan (similar) keessatti cinaawwan walfakkaatan reeshoo wal-qixa qabu: AB/EF = BC/FG = ... Kofawwan walfakkaatan immoo wal-qixa ta'u malee (S(<A)=S(<E), S(<B)=S(<F) jechuudhaan, kutaa gama tokkoon kutaa gama biraatti osoo hin ta'in). B dogongoradha (A'n E waliin wal-simu, H waliin miti). C sirrii miti sababiin reeshoon sirriitti hin barreeffamne. Kanaafuu deebiin sirriin A.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Rog-sadee DEF keessatti S(<D)=70°, safartuun kofa alaa (exterior angle) alaa varteeksii F=120°. S(<E) meeqa?",
      options: ["70°", "60°", "80°", "50°"],
      correctOptionIndex: 3,
      explanation: "Kofni alaa varteeksii F=120° yoo ta'e, kofni keessaa F = 180−120 = 60°. Ida'amni kofa rog-sadee 180° waan ta'eef: S(<E) = 180 − 70 − 60 = 50°.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Kanneen armaan gadii keessaa dheerinni rogoota rog-sadee kofa sirrii ta'e kan kami?",
      options: ["6cm, 9cm, 12cm", "3cm, 2cm, √5cm", "4cm, 2√5cm, 7cm", "10cm, 8cm, 12cm"],
      correctOptionIndex: 1,
      explanation: "Seera Pythagoras (a²+b²=c²) fayyadamnee tilmaamna: A: 6²+9²=117 ≠ 12²=144. B: 2²+(√5)²=4+5=9=3² ✓. C: 4²+(2√5)²=16+20=36≠7²=49. D: 8²+10²=164≠12²=144. Kanaafuu B qofti kofa sirrii qaba.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Geengoo tokko keessatti raadiyeesin 13cm, dheerinni koordii 10cm. Koordiin kun handhuura geengoo irraa hammam fagaata?",
      options: ["12cm", "10cm", "5cm", "√69cm"],
      correctOptionIndex: 0,
      explanation: "Handhuura irraa gara koordiitti sararri hir'isu (perpendicular) koordii walqixa gargar qooda: 10/2=5cm. Rog-sadee sirrii uumama, raadiyeesin (13) hypotenuse. d² + 5² = 13² → d² = 169−25=144 → d=12cm.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Mensureshaanii",
      questionText: "Silindarii oleen isaa 8cm, raadiyeesin isaa 5cm. Bal'inni dirraa cinaa (lateral surface area) isaa meeqa?",
      options: ["50π cm²", "80π cm²", "130π cm²", "200π cm²"],
      correctOptionIndex: 1,
      explanation: "Bal'ina dirraa cinaa silindarii = 2πrh = 2π(5)(8) = 80π cm². (Yoo bal'ina dirraa guutuu gaafatame ta'e, 2πrh + 2πr² = 130π cm² ta'a; gaaffiin kun garuu bal'ina cinaa ykn dirraa waliigalaa gaafachuu danda'a — filannoo C (130π) bal'ina dirraa waliigalaa dha.)",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Kanneen armaan gadii keessaa kan soba ta'e kami?",
      options: [
        "Sararri taanjantiifi raadiyeesin tuqaa taanjantummaa irratti waliif perpeendikuulaariidha",
        "Koordiin geengoo kamiyyuu diyaameetirii ni caala",
        "Sararri seekantii kamiyyuu koordii geengoo ofkeessaa qaba",
        "Geengoo tokko keessatti koordiiwwan lama walitti galoo yoo ta'an, handhuura geengoo irraa walqixa fagaatu"
      ],
      correctOptionIndex: 1,
      explanation: "Himni B soba dha: koordiin diyaameetirii caaluu hin danda'u — diyaameetirri koordii hunda caalaa dheeraadha (diyaameetirri koordii guddaa dha, isa hunda caalu). Himootni kaan (A, C, D) dhugaa dha.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Piroobaabiliitii",
      questionText: "Dinaarri tokko si'a sadi darbatame. Carraan fakkii namaa si'a lama argachuu meeqa?",
      options: ["1/4", "5/8", "1/2", "3/8"],
      correctOptionIndex: 3,
      explanation: "Dinaarri si'a sadi darbachuun kutaalee 8 (2³) qaba. Fakkii namaa si'a lama argachuuf haala danda'amu C(3,2)=3. Kanaafuu carraan = 3/8.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Tuuta",
      questionText: "Yoo M = {a, 5, b, 7, 6} ta'e, tuutni M citoota sirrii (proper subsets) tuuta meeqa qaba?",
      options: ["32", "64", "24", "31"],
      correctOptionIndex: 3,
      explanation: "Tuutni M elementoota 5 qaba. Tuuta hunda (subsets) lakkaawuun 2⁵=32. Citoonni sirrii (proper subsets) tuuta M mataa isaa hin dabalatan, kanaafuu 32−1=31.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Tuuta",
      questionText: "b(A)=30, b(B)=15 fi b(A∩B)=10 yoo ta'e, b(A∪B) meeqa?",
      options: ["55", "30", "45", "35"],
      correctOptionIndex: 3,
      explanation: "Seera waliigalaa: b(A∪B) = b(A)+b(B)−b(A∩B) = 30+15−10 = 35.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Reeshoo",
      questionText: "Reeshoon lakkoofsota lamaa 2:3, ida'amni lakkoofsota kanneenii 55. Lakkoofsota lamaan keessaa inni xiqqaan meeqa?",
      options: ["33", "44", "11", "22"],
      correctOptionIndex: 3,
      explanation: "Reeshoo 2:3 jechuun kutaa 5 (2+3). Kutaa tokko = 55/5 = 11. Lakkoofsi xiqqaan = 2×11 = 22.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Aljebraa",
      questionText: "Ida'amni lakkoofsota pozatiivii intiijerii walitti aanan sadii 78 yoo ta'e, lakkoofsi inni guddaan meeqa?",
      options: ["29", "25", "27", "30"],
      correctOptionIndex: 2,
      explanation: "Lakkoofsota walitti aanan sadii: n−1, n, n+1. Ida'amni = 3n = 78 → n=26. Inni guddaan = n+1 = 27.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Rektaangilii ABCD keessatti dheerinni sarbii (diagonal) AC = 5x+12 fi sarbii BD = 8x+3 yoo ta'e, gatiin 'X' meeqa?",
      options: ["2", "5", "3", "6"],
      correctOptionIndex: 2,
      explanation: "Rektaangilii keessatti sarbiiwwan (diagonals) lamaan walqixa: 5x+12 = 8x+3 → 12−3 = 8x−5x → 9=3x → x=3.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Joomootrii",
      questionText: "Kanneen armaan gadii keessaa kan soba ta'e kami?",
      options: [
        "Roombasiin paraleellogaraamiidha",
        "Iskuweerin roombasiidha",
        "Reektaangilii hundi iskuweeridha",
        "Reektaangilii hundi paraleellogaraamiidha"
      ],
      correctOptionIndex: 2,
      explanation: "Himni C soba dha: reektaangilii hundi iskuweerii miti (iskuweerin cinaawwan walqixa qaba, garuu reektaangilonni hundi cinaawwan walqixa hin qaban). Himoonni A, B, D dhugaa dha — kunneen hundi rog-afree addaa (special parallelograms) waliigala paraleellogaraamii keessa jiraachuu isaanii ibsu.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Lakkoofsota",
      questionText: "HWX (GCF) fi HWG'n (LCM) lakkoofsota 24 fi 36 waldura duubaan meeqa?",
      options: ["36, 6", "12, 6", "44, 12", "72, 12"],
      correctOptionIndex: 3,
      explanation: "24 = 2³×3, 36 = 2²×3². HWX (GCF) = 2²×3 = 12. HWG (LCM) = 2³×3² = 72. GCF fi LCM walduraa duubaan yeroo gaafatamu, LCM=72, GCF=12.",
      isFree: false,
    },
    {
      subject: "Herrega",
      topic: "Istatisiksii",
      questionText: "Barsiisaan umurii barattootaa daree keessaa 14, 15, 16, 18 jedhee tarreesse. Deddeebi'iinsi (frequency) umurii walduraa duubaan 8, 10, 5, 7 ta'e, giddu-galeessi (mean) umurii barattoota daree keessa jiranii meeqa?",
      options: ["15.5", "15", "16", "7.5"],
      correctOptionIndex: 1,
      explanation: "Giddu-galeessa (mean) = Σ(umurii × deddeebi'iinsa) / Σ(deddeebi'iinsa) = [(14×8)+(15×10)+(16×5)+(18×7)] / (8+10+5+7) =[112+150+80+126]/30 = 468/30 = 15.6 ≈ inni filannoo keessatti dhiyaatu 15.",
      isFree: false,
    },

    // Saayinsii waligalaa Subject
    {
      subject: "Saayinsii",
      topic: "Biqiltoota fi Neefka/Qaama Namaa",
      questionText: "Foormulaa ilkaan nama ga'eessaa kan agarsiisu kami?",
      options: ["3131/3121", "2123/2123", "0233/1233", "3232/3232"],
      correctOptionIndex: 1,
      explanation: "Foormulaan ilkaan nama ga'eessaa 2123/2123 dha. Kunis (Incisors: 2, Canines: 1, Premolars: 2, Molars: 3) gubbaa fi jalaa gama tokkoon kan ibsudha. Walumaagalaan ilkaan 32 ta'u.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Ji'oogiraafii",
      questionText: "Laggeen addunyaa keessaa inni kamtu dheeraa dha?",
      options: ["Laga Amaazoon", "Laga Naayilii (Abbaayyaa)", "Laga Yaangitsee", "Laga Misisiipii"],
      correctOptionIndex: 1,
      explanation: "Laga Naayilii (Abbaayyaa) kiilomeetira 6,650 dheerachuu isaatiin laggeen addunyaa keessaa hundarra dheeraa jedhamee fudhatama.",
      isFree: true,
    },
    {
      subject: "Saayinsii",
      topic: "Hawaa",
      questionText: "Pilaaneetota sirna solar keessaa 'Red Planet' (Pilaaneetii Diimaa) jedhamuun kan beekamu kami?",
      options: ["Veenus", "Maarsii", "Juupitar", "Saturn"],
      correctOptionIndex: 1,
      explanation: "Maarsii sababa ayiren okosaayidii (salamtaa) fuula isaa irratti argamuun diimaa fakkaatee mul'ata, kanaanis Pilaaneetii Diimaa jedhama.",
      isFree: true,
    },
    {
      subject: "Saayinsii",
      topic: "Seenaa",
      questionText: "Waraanni Adwaa yoom ta'e, yeroo sana Itoophiyaan Xaaliyaanii koloneeffattuu injifatte?",
      options: ["1889", "1896", "1935", "1941"],
      correctOptionIndex: 1,
      explanation: "Waraanni Adwaa Bitootessa 1, 1896 ta'ee gootota Itoophiyaaf injifannoo guddaa argamsiise.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Maayikrooskooppii",
      questionText: "Yoo qubee 'b' maayikirooskooppii jala keenye fakkaattiin qubee kanaa isa kam ta'ee nutti mul'ata?",
      options: ["b", "q", "d", "p"],
      correctOptionIndex: 2,
      explanation: "Maayikirooskooppiin ergaa (fakkii) sirna leensii isaatiin waan garagalchuuf, fakkiin argamu ol-gadii fi bitaa-mirgatti garagalee mul'ata (inverted image, 180° rotation). Qubeen 'b' yoo 180° garagalfame 'd' ta'a. Kanaafuu deebiin sirriin 'd' dha.",
      isFree: true,
    },
    {
      subject: "Saayinsii",
      topic: "Seelota",
      questionText: "Fayidaa isaa wajjin kan sirrii walitti hin firoomne isa kami?",
      options: [
        "Seelota narvii → Dhaamsa dabarsuu",
        "Seelota dhiiga diimaa → Oksijiinii geejjibuu",
        "Seelota xannachaa → Dhukkuba ittisuu",
        "Seelota maashaa → sochii uumuu"
      ],
      correctOptionIndex: 2,
      explanation: "Seelonni xannachaa (nerve cells) dhukkuba ittisuuf hin fayyadan — hojiin isaanii dhaamsa (impulse) geejjibuudha, akkuma filannoo A ibsutti. Dhukkuba ittisuun hojii seelota dhiigaa adiiti (white blood cells). Kanaafuu himni C walitti hin firoomne (soba dha), deebiin sirriin C.",
      isFree: true,
    },
    {
      subject: "Saayinsii",
      topic: "Soorata",
      questionText: "Dammi gosa kaarboohaayidireetii kami?",
      options: [
        "Sukkaar-tokkee (monosaccharide)",
        "Sukkaar-lamee (disaccharide)",
        "Sukkaar-baay'ee (polysaccharide)",
        "Hunduu deebiidha"
      ],
      correctOptionIndex: 3,
      explanation: "Dammi (honey) walmakaa sukkaaroota adda addaa of keessaa qaba: fruktoosii fi glukoosii (sukkaar-tokkee/monosaccharides) irra caalaatti of keessaa qaba, xiqqoo sukiroosii (disaccharide) fi kaarboohaayidireetota biroos qabaachuu danda'a. Kanaafuu deebiin walii galaa 'hunduu' ta'uu danda'a.",
      isFree: true,
    },
    {
      subject: "Saayinsii",
      topic: "Soorata",
      questionText: "Kaanneen armaan gadii keessaa kamtu sirrii miti?",
      options: [
        "Yaalii sukkaar-tokkee → Benediiktii",
        "Yaalii istaarchii → Bulbula ayoodiinii",
        "Yaalii pirootiinii → Bulbula biyuureetii",
        "Yaalii Coomaa fi zayitii → Benediiktii"
      ],
      correctOptionIndex: 3,
      explanation: "Yaaliin Benediiktii (Benedict's test) sukkaaroota hir'isan (reducing sugars) adda baasuuf fayyada, coomaa fi zayitii (fats and oils) adda baasuuf miti. Coomaa fi zayitii adda baasuuf yaalii 'grease spot test' ykn 'Sudan III' fayyadamu. Kanaafuu himni D sirrii miti; sirriin, yaalii istaarchii bulbula ayoodiiniin, pirootiinii biyuureetiin, sukkaar-tokkee immoo Benediiktiin qorama.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Bullaa'insa Nyaataa",
      questionText: "Gosoota nyaataa erga bullaa'anii booda kan itti jijjiiraman sirrii kan hin taane kami?",
      options: [
        "Istaarchii —(Amilaasii)→ Maaltoosii",
        "Pirootiinii —(Peepsiinii)→ Peeptoonii",
        "Liipiidii —(Liipeesii)→ Faatii asiidii fi giliiseroolii",
        "Maaltoosii —(Maalteesii)→ Guluukoosii fi furuktoosii"
      ],
      correctOptionIndex: 3,
      explanation: "Ensaayimiin Maalteesiin (maltase) maaltoosii gara guluukoosii lamaatti (glucose + glucose) qooda, guluukoosii fi furuktoosii miti. Guluukoosii fi furuktoosiin argamu yeroo sukiroosiin (sucrose) ensaayimii suukreesiin (sucrase) qoodamu. Kanaafuu himni D sirrii miti.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Sirnakkoo",
      questionText: "Sirnakkoo keessatti qopheessitoonni:",
      options: [
        "Gulantaa soorata arfaffaa",
        "Gulantaa soorata tokkoffaa",
        "Gulantaa soorata sadaffaa",
        "Gulantaa soorata lammaffaa"
      ],
      correctOptionIndex: 1,
      explanation: "Qopheessitoonni (producers, fkn biqiltoota) anniisaa aduu fudhatanii nyaata (soorata) ofuma isaaniitiif tolfatu — kanaafuu gulantaa (trophic level) tokkoffaa irratti argamu. Isaan irratti kan hirkatan (consumers) gulantaa lammaffaa, sadaffaa, fi kkf ta'u.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Fotosinteesisi",
      questionText: "Yeroo footoosinteesisii oksijiiniin gara alaatti bahu kam irraa dhufa?",
      options: ["CO₂", "H₂O", "C₆H₁₂O₆", "Hunduma irraa"],
      correctOptionIndex: 1,
      explanation: "Yeroo footoosinteesisii, oksijiinii kan gara alaatti bahu bishaan (H₂O) yommuu addaan cabu (photolysis of water) dha — kunis marsaa ifaa (light reactions) keessatti raawwata. Kaarbon-daayoksaayidii (CO₂) fi guluukoosiin (C₆H₁₂O₆) marsaa ifa-maleessaa (dark reactions/Calvin cycle) keessatti hirmaatu, oksijiinii hin kennan.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Ramaddii Uumamaa",
      questionText: "Maqaa saayinsii Feelis doomastiikasii jedhu keessatti jechi 'doomastiikasii' jedhu maal bakka bu'a?",
      options: ["Warra", "Oordarii", "Qaccee", "Sanyii"],
      correctOptionIndex: 3,
      explanation: "Maqaan saayinsaawaa (binomial nomenclature) jecha lama qaba: maqaa qaccee (genus) fi maqaa sanyii (species). 'Feelis' maqaa qaccee (Genus: cats), 'doomastiikasii' maqaa sanyii (species epithet) ta'ee saree-hoolaa (domestic cat, Felis domesticus/catus) agarsiisa.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Anniisaa Seelii",
      questionText: "Anniisaan qaama keessatti kuufamuudhaan dalagaadhaaf qopheedhi ta'e kami?",
      options: ["ATP", "ADP", "DNA", "AMP"],
      correctOptionIndex: 0,
      explanation: "ATP (Adenosine Triphosphate) 'yuuniitii anniisaa seelii' jedhamee beekama; anniisaa kuufamee dalagaa seelii adda addaaf qopheedha. ADP fi AMP kutaawwan ATP erga anniisaan gadi dhiifamee booda argaman, DNA immoo seenaa jenetiksii (genetic information) qabata malee anniisaa hin kuufatu.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Wal-horata",
      questionText: "Zaayigootiin gosa seelii meeqa irraa uumama?",
      options: ["Baay'ee", "1", "2", "4"],
      correctOptionIndex: 2,
      explanation: "Zaayigootiin (zygote) walitti dhufeenya seelii kormaa (sperm) tokkoo fi seelii dubaraa (egg) tokkoo irraa uumama — kanaafuu gosa seelii lama (2) irraa uumama.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Wal-horata",
      questionText: "Dubartiin waggaa 30 takka Fulbaana 15 marsaa laguu yoo argite, marsaa itti aanu yoom argitii?",
      options: [
        "Onkololeessa 17",
        "Onkololeessa 28",
        "Onkololeessa 13",
        "Onkololeessa 15"
      ],
      correctOptionIndex: 2,
      explanation: "Marsaan laguu (menstrual cycle) tiyoraadhaan guyyaa 28 fudhata. Fulbaana 30 guyyaa qaba. Fulbaana 15 irraa hanga Fulbaana 30tti guyyaa 15, hafe (28-15=13 guyyaa) Onkololeessa keessatti lakkaawwama: Onkololeessa 13ffaa.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Rukkina",
      questionText: "Rukkinni Aluminiyeemii 2.7 g/ml. Qubeen Aluminiyeemii 54g ta'ee meeqaa?",
      options: ["10 ml", "20 ml", "40 ml", "80 ml"],
      correctOptionIndex: 1,
      explanation: "Rukkina (density) = Hanga (mass) / Qabee (volume). Kanaafuu Qabee = Hanga/Rukkina = 54g / 2.7g/ml = 20 ml.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Kompaawundoota",
      questionText: "Amaloota waliigalaa kompaawundootaa kan hin taane kami?",
      options: [
        "Qabxii baqinaa fi murtaa'aa qaba",
        "Ruuqooleen isaa amaloota isaanii eegatanii hafu",
        "Foormulaa dhaabbataa ta'e qabu",
        "Ruuqooleen isaa adeemsa keemikaalaa qofaan gargar ba'u"
      ],
      correctOptionIndex: 1,
      explanation: "Kompaawundiin (compound) yeroo uumamu ruuqoonni (elements) walitti dhufan amala isaanii dhuunfaa dhabu, amala haaraa argatu. Kanaafuu himni B ('ruuqooleen amaloota isaanii eegatu') sirrii miti — kunis amala 'walmakaa' (mixture) ti, kan kompaawundii miti.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Foormulaa Keemikaalaa",
      questionText: "Foormulaan keemikaalaa Ayiran(II) Salfeetii isa kami?",
      options: ["Fe₃(SO₃)₂", "FeSO₃", "Fe₃(SO₄)₂", "FeSO₄"],
      correctOptionIndex: 3,
      explanation: "Ayiran(II) jechuun ion Fe²⁺, salfeetiin (sulfate) SO₄²⁻ dha. Chaarjiiwwan lamaan waljijjiiruu waan danda'aniif (2+ fi 2−), foormulaan salphaa FeSO₄ ta'a.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Atoomii",
      questionText: "Tiyoorii atoomawaa Daaltan keessaa yaadni dogoggora ta'e kami?",
      options: [
        "Atoomonni elementii tokko, atoomota elementii biroo irraa adda",
        "Atoomonni reeshoo lakkoofsa xiqqaatiin walnyaatu",
        "Atoomonni uumamuu hin danda'an",
        "Atoomonni gargar hin qoodaman/hin qoqqoodaman"
      ],
      correctOptionIndex: 3,
      explanation: "Tiyooriin Daaltan (Dalton) atoomiin gargar hin qoqqoodamu (indivisible) jedhee yaada; garuu qorannoon booda argame (piroototnii, elektiroonii, niwutiroonii) atoomiin qaamolee xixiqqaa (subatomic particles) of keessaa qabaachuu isaa mul'iseera. Kanaafuu yaada Daaltan keessaa D dogoggora ta'e dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Gabatee Peeriyodikii",
      questionText: "Elementiin lakkoofsa atoomaawaa isaa 35 ta'e gabatee peeriyodikii keessatti tarree_ fi garee_ keessatti argama.",
      options: ["4, VA", "5, IVA", "4, VIIA", "7, IVA"],
      correctOptionIndex: 2,
      explanation: "Elementiin lakkoofsa atoomaawaa 35 qabu Bromine (Br) dha. Konfiguraasiin elektiroonii isaa [Ar]3d¹⁰4s²4p⁵ waan ta'eef, tarree (period) 4ffaa, garee (group) VIIA (haaloojeenota) keessatti argama.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Alkoolii",
      questionText: "Dhugaatii alkoolii hunduu ____ of keessaa qabu.",
      options: ["Itaanoolii", "Meetaanoolii", "Butaanoolii", "Foormaaliinii"],
      correctOptionIndex: 0,
      explanation: "Dhugaatiiwwan alkoolii (fkn araqee, biiraa, waayinii) hundi itaanoolii (ethanol, C₂H₅OH) of keessaa qabu — kunis alkoolii dhugaatii keessatti fayyadamamuudha. Meetaanoolli (methanol) summii ta'ee dhugaatiitti hin fayyadamu.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Asiidii fi Beezii",
      questionText: "Beezii bishaan dhabeessa kan ta'e kami?",
      options: ["NaOH", "HNO₃", "MgO", "Ca(OH)₂"],
      correctOptionIndex: 2,
      explanation: "MgO (Maagniziyeem Ooksaayidii) beezii dhabeessa bishaanii (anhydrous/dry base — oksaayidii metaalaa) dha, waan bishaan of keessaa hin qabneef. NaOH fi Ca(OH)₂ 'hayidiroksaayidoota' (hydroxides, kunis hydrogen-oxygen group qabu), HNO₃ immoo asiidiidha, beezii miti.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Asiidii fi Beezii",
      questionText: "Oksaayidoota cimdii armaan gadii keessaa bishaan wajjin wal-nyaachuun bulbula beezii kennu isa kami?",
      options: ["SO₂ fi CO₂", "Na₂O fi MgO", "CaO fi SO₃", "Al₂O₃ fi P₂O₃"],
      correctOptionIndex: 1,
      explanation: "Na₂O fi MgO oksaayidoota metaalaa (metal oxides) waan ta'aniif bishaan wajjin walnyaatanii bulbulawwan beezii (basic hydroxides — NaOH fi Mg(OH)₂) kennu. SO₂, CO₂, SO₃ oksaayidoota metaala-maleessaa (non-metal oxides) waan ta'aniif bishaan wajjin asiidota (acidic solutions) kennu.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Laaqii",
      questionText: "Biroonziin laaqii _ fi _ ti.",
      options: ["Zn fi Cu", "Cu fi Sn", "Pb fi Sn", "Au fi Ag"],
      correctOptionIndex: 1,
      explanation: "Biroonzii (bronze) laaqii (alloy) naasii (Cu = Copper) fi tinii (Sn = Tin) irraa uumama. (Zn fi Cu walitti dhufuun 'Biraasii/Brass' uumu, kun immoo Biroonzii irraa adda dha.)",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Amaloota Eelementootaa",
      questionText: "Kan sirrii hin taane kami?",
      options: [
        "Diyaamandiin ittisoo hoo'aa ti",
        "Foosfarasii diimaan gilleensa keessatti hin bobaa'u",
        "Kalaasiyoomiin sibiila al-miraalii dha",
        "Salfariin gaggeessituu elektiriikii miti"
      ],
      correctOptionIndex: 0,
      explanation: "Diyaamandiin (diamond) sirriitti gaggeessituu ho'aa (excellent thermal conductor) dha, ittisoo (insulator) miti — bakka diyaamandii gaariitti fayyadaman keessaa tokko kanuma. Kanaafuu himni A sirrii miti.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Rukkina",
      questionText: "Rukkina wantootaa (qaamolee fiizikaalaa) armaan gadii ilaalchisee kamtu sirrii dha?",
      options: [
        "Jajjaboo > Dhangala'oo > Gaasota",
        "Jajjaboo < Dhangala'oo < Gaasota",
        "Dhangala'oo > Jajjaboo > Gaasota",
        "Hunduu deebii dha"
      ],
      correctOptionIndex: 0,
      explanation: "Waliigalatti, rukkinni (density) jajjaboo (solids) irra caalaa dha, itti aansee dhangala'oo (liquids), gaasonni (gases) immoo isaan hunda caalaa gad-aanaadha — kunis walitti dhihiina molekiyuulota isaanii irraa kan ka'e. Kanaafuu Jajjaboo > Dhangala'oo > Gaasota.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Sochii",
      questionText: "Motorri tokko fageenya 1000m gara dhihaatti yeroo sekondii 30 tti fudhate. Ariitiin motora kanaa meeqa?",
      options: ["0.03m/s", "0.33m/s", "33m/s", "33.3m/s"],
      correctOptionIndex: 3,
      explanation: "Ariitii (speed) = Fageenya / Yeroo = 1000m / 30s = 33.3 m/s.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Sochii",
      questionText: "Konkolaataan tokko ariitii wal-fakkaataadhaan yoo deeme guulli isaa maal ta'a?",
      options: ["Ni dabala", "Ni hir'isa", "Wal-fakkaata (0/hin jijjiiramu)", "Guulaa hin qabu"],
      correctOptionIndex: 2,
      explanation: "Guulli (acceleration) jijjiirama ariitii (velocity) yeroo waliin ibsa. Yoo ariitiin wal-fakkaataa (constant) ta'e, jijjiiramni hin jiru, kanaafuu guulli isaa zeeroo (ni hin jiru/wal-fakkaataadha).",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Inershiyaa",
      questionText: "Wanti qaamni tokko mormii qaama tokkoo kan haala sochii yookiin boqonnaa isaa keessaa akka turu godhu maali?",
      options: ["Ulfaatina", "Inershiyaa", "Hanga", "Momantamii"],
      correctOptionIndex: 1,
      explanation: "Inershiyaan (inertia) amala qaama tokkoo kan haala sochii (ykn boqonnaa) isaa akkuma jirutti itti fufuuf barbaadu ibsa — Seera Niwuutan Tokkoffaa (Newton's First Law) kana ibsa.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Humna",
      questionText: "Humni goochaa (F) 'm' taatee guula 'a' irratti hanga walfakkaatuun taatee guulaa dachaa afuriin yoo guddate, humni hammam ta'a?",
      options: ["2F", "F", "4F", "¼F"],
      correctOptionIndex: 2,
      explanation: "F = ma. Yoo hangi (m) walfakkaatuu ta'e, guulli (a) dachaa afurii (4x) yoo dabale, humni (F) proporshinaalii guulaaf waan ta'eef, innis dachaa afurii (4F) ta'a.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Hojii fi Anniisaa",
      questionText: "Kubbaan tokko anniisaa 24J qaba, yeroo sekondii 3 keessatti yoo socho'e, humni kubbaa kanaa hoiratu meeqa?",
      options: ["26J/s", "12W", "48W", "8W"],
      correctOptionIndex: 3,
      explanation: "Humni-hojii (power) = Anniisaa/Yeroo = 24J / 3s = 8 Watt (W).",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Ho'a",
      questionText: "Kanneen armaan gadii keessaa foormulaa sirriin gulantaalee tempireechara (temperature) gidduu jiru ibsu isa kami?",
      options: ["Tc = 5/9(TF - 32)", "Tc = 5/9(TF + 32)", "Tc = TK + 273", "Hunduu deebii dha"],
      correctOptionIndex: 0,
      explanation: "Sadarkaa Selsiyeesii (Celsius) gara Faareenhaayitiitiin walitti hidhuuffoormulaan sirriin: Tc = 5/9(TF − 32). Sadarkaa Kelvin gara Selsiyeesiitti: Tc = TK − 273 (kunis foormulaa C irratti dhiyaate irraa adda, kan D dogoggora agarsiisu).",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Sagalee",
      questionText: "Namni tokko fageenya 's' irraa dhaabatee sagalee dhageessise. Yeroo murtaa'e booda sagaleesaa dhagahe. Fageenyi sagaleen deeme, fageenya isaafi wanta sagalee balaqqeessisu gidduu meeqa?",
      options: ["s", "½ s", "2s", "4s"],
      correctOptionIndex: 2,
      explanation: "Sagaleen (echo/qeensa) osoo dhaabbannaa irraa gara wanta balaqqeessisuutti deemee, achii deebi'ee gara nama dhagahuu ni deema — kanaafuu daandiin sagaleen deeme dachaa fageenya (s) tokkoo (2s) ta'a.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Maagineetiizimii",
      questionText: "Maagineetiin yeroo jalqabaaf argame maal jedhamee beekama?",
      options: ["Koorsaanii", "Dhagaa maagineetii", "Ippiididimisii", "Ujummoo sanyii kormaa"],
      correctOptionIndex: 1,
      explanation: "Maagineetiin uumamaan argamu (naturally occurring magnetite/lodestone) 'dhagaa maagineetii' jedhamee beekama; Giriik biyya Magnesia jedhamu keessatti argameera.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Sagalee",
      questionText: "Saffisni sagaleen maatarii keessatti qabu guddina irraa gara xiqqaatti kan agarsiisu isa kami?",
      options: [
        "Gaasii > Dhangala'oo > Jajjaboo",
        "Dhangala'oo > Gaasii > Jajjaboo",
        "Jajjaboo > Gaasii > Dhangala'oo",
        "Jajjaboo > Dhangala'oo > Gaasii"
      ],
      correctOptionIndex: 3,
      explanation: "Sagaleen (sound waves) dhangala'oo fi jajjaboo keessatti dafee deema, gaasota keessatti immoo suuta deema — sababiin isaas walitti dhihiina moleekiyuulotaa. Kanaafuu: Jajjaboo > Dhangala'oo > Gaasii.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Safara",
      questionText: "Meeshaalee safaraa armaan gadii keessaa dheerina safaruuf kan tajaajilu isa kami?",
      options: ["Termoomeetira", "Varniyeer kaalipparii", "Niiwuton meetira", "Ammeetira"],
      correctOptionIndex: 1,
      explanation: "Varniyeer kaalipparii (Vernier caliper) meeshaa dheerina/dhangala fageenya xixiqqaa sirriitti safaruuf oolu dha. Termoomeetiran ho'a, Niiwuton meetiran humna, Ammeetiran immoo elektirikii (current) safara.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Safara",
      questionText: "Fageenyi Finfinneedhaa hamma magaalaa Asallaatti jiru 159km yoo ta'e, fageenyi kun ____ m ta'a.",
      options: ["15,900 dam (dekaameetira)", "1,590 dam", "15.9 dam", "1.59 dam"],
      correctOptionIndex: 0,
      explanation: "Yaadannoo: gaaffiin kun dhugaadhaan yuuniitii 'dekaameetira (dam)' gaafata, hin taane meetira caalaa (1km=1000m osoo ta'ee, 159km=159,000m ta'a; kun garuu filannoowwan waliin wal hin simu). Yuuniitii dekaameetiraan (1km=100dam), 159km=15,900dam ta'a — kunis filannoo A waliin walsimuudha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Inershiyaa",
      questionText: "Hunma 50N ta'een wanta hangi isaa guddaa ta'e sochoosuurra wanta hanga isaa xiqqaa ta'e sochoosuun salphaa kan ta'eef maaliif?",
      options: [
        "Hangi guddaan inershiyaa xiqqaa waan qabuufidha",
        "Hangi xiqqaan inershiyaa guddaa waan qabuufidha",
        "Hangi xiqqaan inershiyaa xiqqaa waan qabuufidha",
        "Hangii fi inershiyaan hariiroo tokko hin qabani"
      ],
      correctOptionIndex: 2,
      explanation: "Inershiyaan (inertia) hanga (mass) waliin walqixa deema — hangi guddaan inershiyaa guddaa qaba, hangi xiqqaan inershiyaa xiqqaa qaba. Sababiin humni tokko wanta hanga xiqqaa qabu salphaatti sochoosuu danda'u, inershiyaan isaa xiqqaa waan ta'eef.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Humna",
      questionText: "Humni gitamaa hin ta'in wanta hanga isaa 20kg qabu irratti dalagaa'ee yoo guula 4m/s² tiin guulsise, humni irratti dalagaa'e kun hammam ta'a?",
      options: ["5 N", "20 N", "40 N", "80 N"],
      correctOptionIndex: 3,
      explanation: "F = ma = 20kg × 4m/s² = 80N.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Hojii fi Anniisaa",
      questionText: "Baacaan wanta hangi isaa 20kg ta'e irratti hunma 150N dalga dalageessuun fageenya 8m yoo dhiibe, dalagaan wanticha irratti dalageeffame meeqa?",
      options: ["1,600 J", "1.2kJ", "3kJ", "1,200 J"],
      correctOptionIndex: 1,
      explanation: "Dalagaa (work) = Humna × Fageenya = 150N × 8m = 1,200J = 1.2kJ.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Meeshaalee Salphaa",
      questionText: "Saanduqa 60kg ta'e tokko bal'insa habalakaa dheerina 8m fi hojjaa 2m qabu irra sololaachisuun lafatti yoo buufame, reeshiyoon ariitii bal'insa habalakaa meeqa ta'a?",
      options: ["0.25", "4", "8", "16"],
      correctOptionIndex: 1,
      explanation: "Reeshoon ariitii bal'ina habalakaa (velocity ratio/mechanical advantage tiyooretikaalaa) = Fageenya humni deemu / Fageenya baacaan deemu = 8m / 2m = 4.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Maagineetiizimii",
      questionText: "Wantoota armaan gadii keessaa kan maagineetiidhaan hin harkifamne isa kami?",
      options: ["Ayiranii", "Nikeelii", "Koopparii", "Koobaaltii"],
      correctOptionIndex: 2,
      explanation: "Ayiranii (iron), Nikeelii (nickel), fi Koobaaltii (cobalt) sibiiloota feeroomaagineetikii (ferromagnetic) waan ta'aniif maagineetiidhaan ni harkifamu. Koopparii (copper) immoo sibiila maagineetii hin harkifamne (non-magnetic) dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Maagineetiizimii",
      questionText: "Seera maagineetiizimii ilaalchisee kanneen armaan gadii keessaa kan sirrii ta'e isa kami?",
      options: [
        "Bantoowwan maagineetii wal hin fakkaanne wal dhiibu",
        "Bantoowwan maagineetii wal fakkaatan wal dhiibu",
        "Bantoowwan maagineetii walfakkaatan wal harkisu",
        "Hunduu sirriidha"
      ],
      correctOptionIndex: 1,
      explanation: "Seera maagineetiizimii: bantoonni (poles) wal-fakkaatan (kaabaa-kaabaa ykn kibbaa-kibbaa) wal dhiibu; bantoonni wal hin fakkaanne (kaabaa-kibbaa) wal harkisu. Kanaafuu filannoo B qofti sirrii dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Humna",
      questionText: "Kanneen armaan gadii keessaa daayimeenshinii humnaa kan ta'e isa kami?",
      options: ["[MLT⁻²]", "[ML²T⁻²]", "[ML²T⁻¹]", "[MLT⁻¹]"],
      correctOptionIndex: 0,
      explanation: "F = ma. Hangi (mass) daayimeenshinii M qaba, guulli (acceleration) immoo daayimeenshinii LT⁻² qaba (fageenya/yeroo²). Kanaafuu daayimeenshiniin humnaa [MLT⁻²] dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Dhiibbaa",
      questionText: "Ol ka'iinsi lafa irraa adaduma dabalaa adeemuun dhiibbaan atmoosferii ____.",
      options: ["Dabalaa adeema", "Hin jijjiiramu", "Xiqqaachaa adeema", "Dhaabbataadha"],
      correctOptionIndex: 2,
      explanation: "Ol ka'iinsi lafa irraa (altitude) yeroo dabalu, dhiibbaan (pressure) atmoosferii xiqqaachaa adeema — sababiin isaas qilleensi (air) ol'aanaatti wal-xaxaan (density) isaa xiqqaachaa waan deemuufi.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Sirna Dhiigaa",
      questionText: "Dhiigni kaarboondaayoksaayidii baay'ee qabate kutaa qaama adda addaa irraa jalqabee, kutaa onnee kam seena?",
      options: [
        "Veentiriikilii mirgaa",
        "Oorikilii mirgaa",
        "Veentiriikilii bitaa",
        "Oorikilii bitaa"
      ],
      correctOptionIndex: 1,
      explanation: "Dhiigni oksijiinii xiqqaate (deoxygenated, kaarboondaayoksaayidii baay'ee qabu) qaama guutuu irraa walitti qabamee, jiijoolii gurguddaan (vena cava) Oorikilii mirgaatti (right atrium) seena. Achii gara Veentiriikilii mirgaatti darbee, gara sombaatti (lungs) erga qulqullaa'uuf.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Biqiltoota",
      questionText: "Albuudota biyyee keessaa guddina biqiltootaaf hamma xiqqaan barbaachisan (mikironutrients) keessaa isa kami?",
      options: ["Foosfarasii", "Pootaasiyeemii", "Kilooriinii", "Naayitirooginii"],
      correctOptionIndex: 2,
      explanation: "Foosfarasii, Pootaasiyeemii, fi Naayitirooginiin albuudota biqiltoonni hamma guddaan barbaadan (macronutrients). Kilooriiniin immoo hamma xiqqaadhaan barbaachisu (micronutrient) keessatti ramadama.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Hawaa",
      questionText: "Aduun kan ijaaramte irraa (elementoota lamaan aduu keessatti baay'inaan argaman)",
      options: [
        "Hiiliyeemii, Haayidiroojinii",
        "Oksijiinii, Kaarbonii",
        "Salfarii, Filooriinii",
        "Haayidiroojinii, Oksijiinii"
      ],
      correctOptionIndex: 0,
      explanation: "Aduun irra caalaa Haayidiroojinii (~74%) fi Hiiliyeemii (~24%) irraa ijaaramte. Elementoonni kunneen lama hidhamaa nukilariitiin (nuclear fusion) walitti dhufuun anniisaa maddisiisu.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Argannoo Saayinsii",
      questionText: "Saayintistiin sanyii filatamaa mishingaa goginsa dandamatuufi bishaan xiqqaan omisha guddaa kennuu qabatee argate:",
      options: [
        "Dr. Akliiluu Lammaa",
        "Toomaas Edisan",
        "Prof. Gabbisaa Ejjetaa",
        "Albert Anestaayin"
      ],
      correctOptionIndex: 2,
      explanation: "Prof. Gabbisaa Ejjetaan (Gebisa Ejeta) saayintistii jenetiksii Itoophiyaa yoo ta'an, sanyii mishingaa (sorghum) goginsaa fi yaa'a dandamatu, omisha guddaa kennu argachuun badhaasa guddaa 'World Food Prize' jedhamu bara 2009tti injifataniiru.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Biqiltoota fi Neefka/Qaama Namaa",
      questionText: "Foormulaan ilkaan nama ga'eessaa tokko 2 1 2 3 / 2 1 2 3 yoo ta'e, baay'inni ilkaan daadee (incisors) hundaa meeqa ta'a?",
      options: ["4", "6", "8", "12"],
      correctOptionIndex: 2,
      explanation: "Foormulaan ilkaanii lakkoofsa gosa ilkaanii tokkoo kutaa afraffaa (quadrant) tokko keessatti argamu agarsiisa (lakkoofsi jalqabaa = Daadee/Incisors = 2). Afaan namaa kutaawwan afur (bitaa-mirga fi ol-gadii) waan qabuuf: 2 daadee × 4 kutaa = 8.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Foormulaa Keemikaalaa",
      questionText: "Kompaawundoota armaan gadii keessaa kan maqaan isaa foormulaa waliin sirrii ta'e kami?",
      options: [
        "KCO₃: Pootaasiyeem Kaarbooneetii",
        "AlNO₃: Aluminiyeem Naayitireetii",
        "NaPO₄: Soodiyeem Foosfeetii",
        "CaSO₄: Kaalsiyeem Salfeetii"
      ],
      correctOptionIndex: 3,
      explanation: "Kaalsiyeem (Ca²⁺) fi Salfeetii (SO₄²⁻) chaarjii walqixxaataniif reeshoo 1:1n walitti dhufu, foormulaan CaSO₄ sirrii dha. Filannoowwan kaan foormulaa sirrii miti: Pootaasiyeem Kaarbooneetiin sirriitti K₂CO₃ (K⁺ tokkoon CO₃²⁻ balanseessuu waan hin dandeenyeef), Aluminiyeem Naayitireetiin Al(NO₃)₃ (Al³⁺ waliin NO₃⁻ sadii barbaachisa), Soodiyeem Foosfeetiin Na₃PO₄ (PO₄³⁻ waliin Na⁺ sadii barbaachisa) ta'uu qaba.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Walqixxaatoo Keemikaalaa",
      questionText: "Walqixxaa keemikaalaa NH₃ + O₂ → NO + H₂O madaalamee, koofishaantiin 'H₂O' meeqa ta'a?",
      options: ["3", "4", "5", "6"],
      correctOptionIndex: 3,
      explanation: "Walqixaan yeroo madaalamu: 4NH₃ + 5O₂ → 4NO + 6H₂O. Kanaafuu koofishaantiin H₂O 6 dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Seelii",
      questionText: "Caasaa seelii keessaa bakki gubamni sooratamaa itti geggeeffamuufi anniisaan seelii itti omishamu isa kami?",
      options: [
        "Raayiboosoomii",
        "Maayitookondoriyaa",
        "Niwukilasii",
        "Vaakiyuulii"
      ],
      correctOptionIndex: 1,
      explanation: "Maayitookondoriyaan (mitochondria) 'mootora seelii' (powerhouse of the cell) jedhamee beekama; achitti sooratni gubamee (cellular respiration) ATP omishama.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Teeknooloojii",
      questionText: "Bu'aa teeknooloojii baayooloojii keessatti itti fayyadamnu kan ta'e kami?",
      options: ["Raadiyoo", "Xiyyaara", "Bilbila", "Inkubeetarii"],
      correctOptionIndex: 3,
      explanation: "Inkubeetariin (incubator) meeshaa baayooloojii/fayyaa keessatti hoo'a fi haala qabeenya jiraatoota (fkn daa'ima dhalate ykn kultura seelii) too'achuuf oolu, kanaafuu bu'aa teeknooloojii baayooloojii dha. Kaan (raadiyoo, xiyyaara, bilbila) teeknooloojii fiiziksii/inisiniyeringii biroo irraa argaman.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Mikiroo-orgaanizimoota",
      questionText: "Kanneen armaan gadii keessaa faayidaa raacitii (yeast) kan ta'e kami?",
      options: [
        "Aannan itichuu",
        "Biyyee gabbisuu",
        "Bukoon akka bukaa'u gochuu",
        "Qoricha qopheessuu"
      ],
      correctOptionIndex: 2,
      explanation: "Raacitiin (yeast) fermenteeshinii geggeessuun bukoo akka bukaa'u (dough to rise) taasisuuf, akkasumas dhugaatii alkoolii omishuuf fayyada — kunis faayidaa isaa beekamaa dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Wal-horata",
      questionText: "Qaamolee walhormaataa dhiiraa keessaa sanyii kormaa kuusee tursiisuuf kan gargaaru isa kami?",
      options: [
        "Yuureetiraa",
        "Qola cidhaanii (scrotum)",
        "Ippiididimisii",
        "Ujummoo sanyii kormaa"
      ],
      correctOptionIndex: 2,
      explanation: "Ippiididimisiin (epididymis) sanyii kormaa (sperm) omishamee erga bahee booda kuufamee/tursifamee itti guddatuu fi gahaa ta'u dha.",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Fayyaa",
      questionText: "Dhiibbaa 'HIV/AIDS'n hawaasa irraan gahu kan ta'e kami?",
      options: [
        "Daa'immaniifi ijoollee abbaafi haadha dhabsiisuu",
        "Galiin namoota dhuunfaa akka dabalu gochuu",
        "Humni misooma biyyaa akka guddatu taasisuu",
        "Dinagdeen biyyaa akka dabalu taasisuu"
      ],
      correctOptionIndex: 0,
      explanation: "HIV/AIDS'n dhiibbaa hamaa hawaasa irraan gahu keessaa tokko, warra du'aniin ijoolleen abbaafi haadha dhabuun kunuunsa maatii malee hafuu (orphans) dha. Filannoowwan kaan dhugaa waliin hin simne (dhiibbaan kun negatiivii dha, positiivii miti).",
      isFree: false,
    },
    {
      subject: "Saayinsii",
      topic: "Wal-horata",
      questionText: "Caasaalee walhormaataa dhalaa namaa irratti iddoo micireen itti dagaaguufi guddatan duubaan kami?",
      options: [
        "Oovaarii (ovary)",
        "Ujummoo oovaarii (fallopian tube)",
        "Gadaameessa (uterus)",
        "Serveeksii (cervix)"
      ],
      correctOptionIndex: 2,
      explanation: "Micireen (embryo) erga fooyya'ee booda gadaameessa (uterus) keessatti hidhachuun (implantation) achitti dagaagaa fi guddachaa deema.",
      isFree: false,
    },

    // English Subject (Ifa Boru and ODA Special Boarding Secondary Schools Grade 9 Entrance Examination)
    {
      subject: "English",
      topic: "Section 1: Reading Comprehension (Walia Ibex passage)",
      questionText: "As an Ethiopian citizen, what do you think is expected from us?",
      options: [
        "Make effort to deforest their habitat",
        "Do nothing",
        "Make effort to conserve",
        "Do something to resettle them"
      ],
      correctOptionIndex: 2,
      explanation: "The passage says conservation efforts are crucial for the Walia Ibex's survival, and calls it a symbol of the balance between humans and nature. This implies citizens should support conservation, not destroy habitat (A), remain passive (B), or relocate the animals (D, which isn't mentioned anywhere in the passage).",
      isFree: true,
    },
    {
      subject: "English",
      topic: "Section 1: Reading Comprehension",
      questionText: "What makes Walia Ibex unique animal?",
      options: [
        "Popular everywhere",
        "No more existing",
        "Only males are poached",
        "Rare species"
      ],
      correctOptionIndex: 3,
      explanation: "The passage opens by describing the Walia Ibex as 'a rare species of Ibex' and later notes 'only a few hundred Walias left in the wild.' This directly supports 'Rare species.' It is not popular everywhere (A), it still exists (B is false), and poaching is mentioned as a general threat, not specific to males only (C).",
      isFree: true,
    },
    {
      subject: "English",
      topic: "Section 1: Reading Comprehension",
      questionText: "Which one of the following is NOT mentioned as a cause for the disappearance of Walia Ibex?",
      options: [
        "Reproducing them in laboratories",
        "Poaching",
        "Habitat loss",
        "Competition with domestic livestock"
      ],
      correctOptionIndex: 0,
      explanation: "The passage lists exactly three causes: 'Habitat loss, competition with domestic livestock, and poaching.' Laboratory reproduction is never mentioned in the passage at all — in fact it would be a conservation method, not a cause of disappearance. So A is correctly the one NOT mentioned.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 1: Reading Comprehension",
      questionText: "When do male Walias rejoin the group?",
      options: [
        "During migration",
        "During mating season",
        "When they attack their enemy",
        "When they graze"
      ],
      correctOptionIndex: 1,
      explanation: "The passage states directly: 'Mature males may lead more lonely lives but stay close to the herd, rejoining during the mating season.' This is an explicit statement in the text, so B is correct.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 1: Reading Comprehension - Vocabulary in context",
      questionText: "The word 'mature' in paragraph 2 means __.",
      options: [
        "young",
        "old",
        "infant",
        "undeveloped"
      ],
      correctOptionIndex: 1,
      explanation: "'Mature' describes adult animals that have fully grown/developed — the closest meaning among the choices is 'old' (as opposed to young/infant/undeveloped). In context, 'mature males' are contrasted with the general herd, implying fully-grown adults.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 1: Reading Comprehension - Vocabulary in context",
      questionText: "The word 'which' in paragraph 1 refers to __.",
      options: [
        "Horn",
        "Females",
        "Males",
        "Walias"
      ],
      correctOptionIndex: 0,
      explanation: "The sentence reads: 'Males are particularly famous for their impressive horns, which are reach up to 110 cm in length.' The pronoun 'which' immediately follows and refers back to 'horns' — it is the horns that reach up to 110cm, not the males, females, or Walias generally.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 2: Vocabulary in Context",
      questionText: "The principal decided to postpone the staff meeting until next Friday due to the urgent workshop. What does the word 'postpone' mean?",
      options: [
        "cancel",
        "put off",
        "speed up",
        "organize"
      ],
      correctOptionIndex: 1,
      explanation: "To 'postpone' something means to delay it or schedule it for a later time. The phrasal verb 'put off' has the exact same meaning.",
      isFree: true,
    },
    {
      subject: "English",
      topic: "Section 2: Vocabulary in Context",
      questionText: "She has an intense passion for reading science fiction novels. The word 'intense' is closest in meaning to __.",
      options: [
        "weak",
        "temporary",
        "strong",
        "unusual"
      ],
      correctOptionIndex: 2,
      explanation: "'Intense' means very strong, extreme, or acute. In this context, an intense passion is a very strong passion.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 2: Vocabulary in Context",
      questionText: "The NGO provided essential food items to the drought-affected families. The opposite of the word 'essential' is __.",
      options: [
        "unnecessary",
        "important",
        "valuable",
        "crucial"
      ],
      correctOptionIndex: 0,
      explanation: "'Essential' means absolutely necessary or extremely important. The opposite (antonym) is 'unnecessary' (not needed).",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 3: Grammar",
      questionText: "If the rain ________, we will go out for a walk in the afternoon.",
      options: [
        "stop",
        "stops",
        "stopped",
        "will stop"
      ],
      correctOptionIndex: 1,
      explanation: "This is a Type 1 Conditional sentence (possible future condition). The 'if'-clause uses the simple present tense ('stops' for the singular subject 'the rain'), and the main clause uses 'will + verb'.",
      isFree: true,
    },
    {
      subject: "English",
      topic: "Section 3: Grammar",
      questionText: "Yesterday, while I ________ my homework, the lights went out suddenly.",
      options: [
        "do",
        "was doing",
        "did",
        "have done"
      ],
      correctOptionIndex: 1,
      explanation: "We use the Past Continuous ('was doing') for an ongoing past action that was interrupted by a shorter action in the simple past ('went out').",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 3: Grammar",
      questionText: "Bontu has been studying at Ifa Boru Boarding School ________ 2024.",
      options: [
        "for",
        "since",
        "until",
        "during"
      ],
      correctOptionIndex: 1,
      explanation: "We use 'since' with the present perfect continuous tense to refer to a specific starting point in time (the year 2024).",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 3: Grammar",
      questionText: "The English exam paper ________ by the teachers right now.",
      options: [
        "is preparing",
        "is prepared",
        "is being prepared",
        "prepared"
      ],
      correctOptionIndex: 2,
      explanation: "The sentence requires the Present Continuous Passive voice ('is being prepared') because the exam paper is the receiver of the action, and 'right now' indicates an action in progress.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 3: Grammar",
      questionText: "This is the student ________ father is a famous surgeon in the referral hospital.",
      options: [
        "who",
        "whom",
        "whose",
        "which"
      ],
      correctOptionIndex: 2,
      explanation: "'Whose' is a possessive relative pronoun used to show that the father belongs to or is related to the student.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 4: Dialogue Completion",
      questionText: "Gadaa: 'Could you lend me your dictionary for a moment?'\nChaltu: '________, here it is.'",
      options: [
        "Of course",
        "I am sorry",
        "No, thank you",
        "I don't think so"
      ],
      correctOptionIndex: 0,
      explanation: "'Of course' is a polite way to agree to a request, followed naturally by 'here it is' as she hands over the dictionary.",
      isFree: true,
    },
    {
      subject: "English",
      topic: "Section 4: Dialogue Completion",
      questionText: "Teacher: 'Well done, Tolasa! You scored 100% on the boarding school entrance exam.'\nTolasa: '________'",
      options: [
        "No problem",
        "Thank you very much",
        "Never mind",
        "I am glad to hear that"
      ],
      correctOptionIndex: 1,
      explanation: "When someone praises or congratulates you, the standard polite response is to say 'Thank you very much'.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 5: Spelling",
      questionText: "Which one of the following words is spelled correctly?",
      options: [
        "Definately",
        "Definitely",
        "Definitly",
        "Deffinately"
      ],
      correctOptionIndex: 1,
      explanation: "The correct spelling is 'Definitely' (spelled with an 'i' after 'n').",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 6: Punctuation",
      questionText: "Which of the following sentences has the correct punctuation?",
      options: [
        "Yes I will come with you to the school library.",
        "Yes, I will come with you to the school library.",
        "Yes, I will come with you, to the school library",
        "Yes I will come with you, to the school library."
      ],
      correctOptionIndex: 1,
      explanation: "A comma should be used after introductory words like 'Yes' or 'No' at the beginning of a sentence.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 7: Paragraph/Sentence Ordering",
      questionText: "Put these sentences in the correct order to make a meaningful paragraph:\n1. Finally, she went to bed feeling satisfied.\n2. First, she completed all her assignments.\n3. After that, she watched a educational video.\n4. Aster had a very busy evening.",
      options: [
        "4,2,3,1",
        "4,3,2,1",
        "2,3,4,1",
        "2,4,3,1"
      ],
      correctOptionIndex: 0,
      explanation: "The paragraph should start with the topic sentence (4 - Aster had a busy evening). Then, sequence transition words help order the rest: 'First' (2), 'After that' (3), and 'Finally' (1). This gives 4,2,3,1.",
      isFree: false,
    },
    {
      subject: "English",
      topic: "Section 7: Paragraph/Sentence Ordering",
      questionText: "Put these sentences in the correct order to make an organized paragraph:\n1. His speech was very interesting.\n2. He advised the students to work hard to be successful in their education.\n3. Last week there was a meeting in our school.\n4. It was addressed by our director and students.",
      options: [
        "3,4,1,2",
        "1,3,4,2",
        "1,3,2,4",
        "3,4,2,1"
      ],
      correctOptionIndex: 0,
      explanation: "Logical narrative order: first set the scene (3 - there was a meeting), then say who spoke (4 - addressed by director/students), then describe the speech (1 - it was interesting), then what was said in it (2 - he advised students). This gives: 3,4,1,2 — a coherent story that flows from event → speaker → quality of speech → content of speech.",
      isFree: false,
    }
  ];

  for (const q of questions) {
    await prisma.question.create({
      data: {
        subject: q.subject,
        topic: q.topic,
        questionText: q.questionText,
        options: q.options,
        correctOptionIndex: q.correctOptionIndex,
        explanation: q.explanation,
        isFree: q.isFree
      }
    });
  }

  console.log("Successfully seeded questions!");
}

main()
  .catch((e) => {
    console.error("Error during seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
